export const navMenu = ['Notice', 'Suggestion'];

export const menu = [
  {
    initial: 'a_category',
    names: [
      'aespa',
      'APRIL',
      'Apink',
      'After School',
      'ASTRO',
      'ATEEZ',
      'AB6IX',
    ],
  },
  {
    initial: 'b_category',
    names: [
      'BTS',
      'Bae_Suzy',
      'BLACKPINK',
      'Berry Good',
      'Blah Blah',
      'BESTie',
      'Brown Eyed Girls',
      'Bling Bling',
      'BIGBANG',
      'Block B',
      'BTOB',
      'B1A4',
      'BAP',
    ],
  },
  {
    initial: 'c_category',
    names: [
      'CL',
      'ChungHa',
      'CLC',
      'Cherry Bullet',
      'Cignature',
      'CAMILA',
      'CRAVITY',
      'CIX',
    ],
  },
  {
    initial: 'd_category',
    names: ['DreamCatcher', 'DIA', 'DONGKIZ'],
  },
  { initial: 'e_category', names: ['EXID', 'ELRIS', 'EXO'] },
  { initial: 'f_category', names: ['fromis_9', 'f(X)', 'F.T.Island'] },
  {
    initial: 'g_category',
    names: [
      'GI-DLE',
      'GFRIEND',
      'Girls Generation',
      'Girls Day',
      'GWSN',
      'GSA',
      'GOT7',
      'Golden Child',
    ],
  },
  {
    initial: 'h_category',
    names: ['HyunA', 'Hello Venus', 'Highlight', 'HOTSHOT'],
  },
  {
    initial: 'i_category',
    names: ['IU', 'IZONE', 'ITZY', 'INFINITE'],
  },
  {
    initial: 'j_category',
    names: ['Jiyeon', 'Jay Park', 'JYJ'],
  },
  {
    initial: 'k_category',
    names: ['Kang_Daniel', 'Kim_Jaehwan'],
  },
  {
    initial: 'l_category',
    names: ['Lovelyz', 'LOONA', 'Ladies Code', 'LABOUM'],
  },
  {
    initial: 'm_category',
    names: ['MAMAMOO', 'MOMOLAND', 'MONSTA X', 'Myname', 'MCND'],
  },
  {
    initial: 'n_category',
    names: ['NATURE', 'NCT', 'NUEST', 'Newkidd'],
  },
  {
    initial: 'o_category',
    names: ['Ong_SeongWu', 'Oh My Girl', 'ONF', 'ONEUS'],
  },
  {
    initial: 'p_category',
    names: ['Park_Jihoon', 'PRECIOUS', 'Pristin', 'PENTAGON'],
  },
  // { initial: 'q_category', names: [] },
  {
    initial: 'r_category',
    names: ['Red Velvet', 'Rocket Punch', 'ROMEO'],
  },
  {
    initial: 's_category',
    names: [
      'Somi',
      'Sunmi',
      'Seolhyun',
      'STAYC',
      'Secret Number',
      'Stellar',
      'SEVENTEEN',
      'SHINee',
      'Super Junior',
      'Stray Kids',
      'SF9',
      'Sechs Kies',
      'Shinhwa',
    ],
  },
  {
    initial: 't_category',
    names: [
      'TWICE',
      'TWEETY',
      'The Boys',
      'TXT',
      'TREASURE',
      'TVXQ',
      'TOO',
      '2PM',
      'Trei',
      'Teen Top',
      '2AM',
    ],
  },
  // { initial: 'u_category', names: [] },
  { initial: 'v_category', names: ['VIXX', 'VICTON', 'Verivery'] },
  {
    initial: 'w_category',
    names: ['WJSN', 'Woo!ah!', 'Weeekly', 'Weki Meki', 'WINNER'],
  },
  // { initial: 'x_category', names: [] },
  // {
  //   initial: 'y_category',
  //   names: [
  //     'Yunho(TVXQ)',
  //     'Yeji(ITZY)',
  //     'Yeri(RedVelvet)',
  //     'Yeeun(CLC)',
  //     'Yuqi((G)I-DLE)',
  //     'YooA(OhMyGirl)',
  //   ],
  // },
  // { initial: 'z_category', names: ['Zico(BlockB)'] },
];
