export const menu = [
  { initial: 'a_category', names: ['AOA', 'fk', 'ok'] },
  { initial: 'b_category', names: ['ok', 'ok', 'ok'] },
  { initial: 'c_category', names: ['ok', 'ok', 'ok'] },
  { initial: 'd_category', names: ['ok', 'ok', 'ok'] },
  { initial: 'e_category', names: ['ok', 'ok', 'ok'] },
  { initial: 'f_category', names: ['ok', 'ok', 'ok'] },
  { initial: 'g_category', names: ['ok', 'ok', 'ok'] },
  { initial: 'h_category', names: ['ok', 'ok', 'ok'] },
  { initial: 'i_category', names: ['ok', 'ok', 'ok'] },
  { initial: 'j_category', names: ['ok', 'sk', 'ok'] },
  { initial: 'k_category', names: ['ok', 'ok', 'ok'] },
  { initial: 'l_category', names: ['ok', 'ok', 'ok'] },
  { initial: 'm_category', names: ['ok', 'ok', 'ok'] },
  { initial: 'n_category', names: ['ok', 'ok', 'ok'] },
  { initial: 'o_category', names: ['ok', 'ok', 'ok'] },
  { initial: 'p_category', names: ['ok', 'ok', 'ok'] },
  { initial: 'q_category', names: ['ok', 'ok', 'vk'] },
  { initial: 'r_category', names: ['ok', 'ok', 'ok'] },
  { initial: 's_category', names: ['ok', 'ok', 'ok'] },
  { initial: 't_category', names: ['ok', 'ok', 'ok'] },
  { initial: 'u_category', names: ['ok', 'ok', 'ok'] },
  { initial: 'v_category', names: ['ok', 'ok', 'ok'] },
  { initial: 'w_category', names: ['ok', 'ok', 'ok'] },
  { initial: 'x_category', names: ['ok', 'ok', 'ok'] },
  { initial: 'y_category', names: ['ok', 'zk', 'ok'] },
  { initial: 'z_category', names: ['ok', 'ok', 'ok'] },
];
